### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by digraph666** [ZSHsh98/EPS-AD#8]
Thank you for your code! The idea of the paper is interesting and the result is competitive. I find that your method demonstrates great performance in detecting the adversarial examples generated by your code , but the detection performance on examples generated by ourselves is poor(70 auroc). I would appreciate it if you could help with our problem.

**Comment by digraph666** [comment]
We use torchattacks to launch attacks on a ResNet pretrained with torchvision.

**Comment by ZSHsh98** [comment]
Thanks for your attention! Could you please provide some detailed code or results here, or email them to me? I will be engaged in solving your confuse. My email is sezhangshuhai@mail.scut.edu.cn.
